<?php

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

$font_awesome_array = array('fa-pencil-square-o',
    'fa-bell',
    'fa-star',
    'fa-heart',
    'fa-globe',
    'fa-ban',
    'fa-dropbox',
    'fa-diamond',
    'fa-anchor',
    'fa-recycle',
    'fa-files-o',
    'fa-gift',
    'fa-asterisk',
    'fa-book',
    'fa-refresh',
    'fa-cc-visa',
    'fa-cc-mastercard',
    'fa-cc-paypal',
    'fa-cc-amex',
    'fa-paypal',
    'fa-credit-card-alt',
    'fa-credit-card',
    'fa-usd',
    'fa-eur',
    'fa-rub',
    'fa-ils',
    'fa-krw',
    'fa-jpy',
    'fa-try',
    'fa-gbp',
    'fa-inr',
    'fa-btc',
    'fa-windows',
    'fa-apple',
    'fa-android',
    'fa-linux',
    'fa-wordpress',
    'fa-drupal',
    'fa-joomla',
    'fa-opencart',
    'fa-opera',
    'fa-chrome',
    'fa-internet-explorer',
    'fa-edge',
    'fa-firefox',
    'fa-safari',
    'fa-html5',
    'fa-css3',
    'fa-google',
    'fa-google-plus',
    'fa-google-plus-square',
    'fa-google-plus-official',
    'fa-facebook',
    'fa-facebook-square',
    'fa-youtube-play',
    'fa-youtube',
    'fa-youtube-square',
    'fa-pinterest-p',
    'fa-pinterest',
    'fa-pinterest-square',
    'fa-linkedin',
    'fa-linkedin-square',
    'fa-twitter',
    'fa-twitter-square',
    'fa-vk',
    'fa-odnoklassniki',
    'fa-instagram',
    'fa-vimeo',
    'fa-vimeo-square',
    'fa-yahoo',
    'fa-reddit',
    'fa-skype',
    'fa-steam',
    'fa-twitch',
    'fa-whatsapp',
    'fa-github',
    'fa-gitlab',
    'fa-envelope-o',
    'fa-share-alt',
    'fa-slack',
    'fa-car',
    'fa-bicycle',
    'fa-motorcycle',
    'fa-ship',
    'fa-train',
    'fa-subway',
    'fa-plane',
    'fa-rocket',
    'fa-thumbs-o-up',
    'fa-thumbs-up',
    'fa-hand-peace-o',
    'fa-usb',
    'fa-wifi',
    'fa-headphones',
    'fa-camera-retro',
    'fa-camera',
    'fa-bluetooth',
    'fa-desktop',
    'fa-mobile',
    'fa-fax',
    'fa-check',
    'fa-times',
    'fa-check-square',
    'fa-check-circle-o',
    'fa-check-circle',
    'fa-lock',
    'fa-cogs',
    'fa-flag',
    'fa-bolt',
    'fa-map',
    'fa-pie-chart',
    'fa-paper-plane',
    'fa-paper-plane-o',
    'fa-file',
    'fa-file-text',
    'fa-file-image-o',
    'fa-file-video-o',
    'fa-area-chart',
    'fa-key',
    'fa-birthday-cake'
);

?>

<div class="huge_it_choose_fa_icon">
    <div class="huge_it_font_awesome_block">
        <span class="huge_it_features_close">+</span>
        <h3><?php _e('Choose Font Awesome Icon', 'hg_pricing_table'); ?></h3>
        <?php foreach ($font_awesome_array as $font_awesome) { ?>
            <label class="font_awesome_label">
                <input type="radio" class="<?php echo $font_awesome; ?>" value="<?php echo $font_awesome; ?>"/>
                <i class="fa <?php echo $font_awesome; ?>" aria-hidden="true"></i>
            </label>
        <?php } ?>
        <div class="clear"></div>
    </div>
    <span class="huge_it_open_fa_icon"><?php _e('Icon', 'hg_pricing_table'); ?></span>
</div>